server:
    port: 7777
    #address: localhost
    context-path: /
    connectionTimeout: 30000
    tomcat:
      max-threads: 500
      uriEncoding: UTF-8
#    compression:
#      enabled: true
#      mime-types: text/html,text/css,application/javascript,application/json

#mapper:
#    mappers:
#        - tk.mybatis.springboot.util.MyMapper
#    not-empty: false
#    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  spider-datasource:
    url: jdbc:mysql://rm-2zeobva30at5p88a1o.mysql.rds.aliyuncs.com:3306/subscribe1?useUnicode=true&characterEncoding=utf-8
    username: subscribe1
    password: subscribe1
#    url: jdbc:mysql://rm-2zeobva30at5p88a1o.mysql.rds.aliyuncs.com:3306/subscribe0?useUnicode=true&characterEncoding=utf-8
#    username: subscribe0
#    password: subscribe0
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 30
    maxWait: 10000
    maxActive: 100
    minIdle: 30
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    removeAbandoned: true
    removeAbandonedTimeout: 180
    logAbandoned: true

  monitor-datasource:
      url: jdbc:mysql://192.168.0.156:3306/spider?useUnicode=true&characterEncoding=utf-8
#      url: jdbc:mysql://192.168.0.156:3306/spider_test?useUnicode=true&characterEncoding=utf-8
      username: mysql
      password: 123456
#      url: jdbc:mysql://192.168.0.50:3306/spider?useUnicode=true&characterEncoding=utf-8
#      username: hive
#      password: hive
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 200
      maxWait: 10000
      maxActive: 1000
      minIdle: 200
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      removeAbandoned: true
      removeAbandonedTimeout: 180
      logAbandoned: true

  http:
    encoding:
      charset: UTF-8
      force: true

zookeeper:
  server: 10.0.0.13:2181
#  server: 192.168.0.50:2181

redis:
#  host: 192.168.0.50
  host: 10.0.0.13
  port: 6379
  password:
  timeout: 10000
  default.db: 0
  pool.maxActive: 500
  pool.maxIdle: 200
  pool.maxWait: 1000
  pool.testOnBorrow: true

site:
  path:
    local: /data/spider-monitor/sites
    svn: svn://192.168.0.12/cms/trunk/sites




